### ISSUE TITLE
Using the data for commercial purposes

### ISSUE THREAD

**Issue by VishwaasHegde** [facebookresearch/TreeNLG#11]
Hello,
Thanks for the paper and the code.
I would like to know if its really possible to use just the data for _commercial purposes_.
If this means that I'd have to buy the license, how much would it cost? and how would I go about buying it?

Thanks

**Comment by mwhite14850** [comment]
Hi, thanks for your interest!  It took some time to figure out who to ask about this.  The answer: please contact Linzy McCartney (lmccartney@fb.com) to discuss.
