### ISSUE TITLE
Can I have some sample data in seq2seq_out.tsv?

### ISSUE THREAD

**Issue by vivian-stars** [facebookresearch/TreeNLG#2]
As title,I can't make smaple data in seq2seq_out.tsv, can someone give me something?

**Comment by jinfengr** [comment]
We have added example files under example/seq2seq_out.tsv, which should give you 0.8511 tree accuracy by running our code.

**Comment by vivian-stars** [comment]
> We have added example files under example/seq2seq_out.tsv, which should give you 0.8511 tree accuracy by running our code.

Thank you, it solved
