### ISSUE TITLE
how to change a sentence to a tree?

### ISSUE THREAD

**Issue by vivian-stars** [facebookresearch/TreeNLG#3]
Hello,
   I need to use my own dataset to train the model or run the compute_tree_acc.py, so my problem is how to make the data as a tree type?And how many the type of attributes?I know query annotation is parse automatically by rules, and can I get these rules?

**Comment by jinfengr** [comment]
Sorry we can not answer this question as it is very problem specific. For dataset creation, please refer to our paper for more details.

**Comment by anushabala** [comment]
Are you asking about the E2E dataset by any chance? We used the following public resources for that:
- The Berkeley neural parser https://github.com/slavpetrov/berkeleyparser
- The Harvard template segmentation https://github.com/harvardnlp/neural-template-gen
- The alignments from the Slug2Slug paper http://www.macs.hw.ac.uk/InteractionLab/E2E/final_papers/E2E-Slug2Slug.pdf (we emailed the authors). 

Essentially though you can follow the rules that the Slug2Slug paper outlines for automatically annotating the responses and extracting the meaning representations from it. We have some code for it but it's not ready for release and we don't expect to maintain it going forward unfortunately.

You could also just try training an automatic parser on the E2E dataset that we have released, and using that to automatically tag any data that you have (assuming of course that you want to tag E2E data, not something else.)

**Comment by anushabala** [comment]
@mj2selina hope that answered your question at least somewhat! Feel free to reopen if you have followup questions.

**Comment by VishwaasHegde** [comment]
@mj2selina were you able to convert a sentence to a tree structure?
