### ISSUE TITLE
Availability of the user raw query

### ISSUE THREAD

**Issue by harkous** [facebookresearch/TreeNLG#4]
Hello,

Thanks for providing these very useful resources. Is there any chance that the users' raw queries would be available as part of the datasets (or a subset of the datasets)? I've seen that the [seq2seq_out.tsv ](https://github.com/facebookresearch/TreeNLG/blob/master/example/seq2seq_out.tsv) example has such questions similar to Table 6 in the paper. So I was wondering if this would be possible to include. That would be highly useful. 

Thanks!
Hamza

**Comment by jinfengr** [comment]
Hi @harkous we have provided user's raw queries to the `Weather` and `Weather_Challenge` dataset. Note that there are some responses in Weather dataset which are not provided a user query (141/17/18/4 for train/val/test/disc_test, respectively). We simply use a "placeholder" token for those missing user queries.

Please close this issue if it resolves your request.

**Comment by harkous** [comment]
Thanks a lot @jinfengr . This is very useful and adds a new area interesting dimension to this dataset.
