### ISSUE TITLE
How to do Prediction in this system?

### ISSUE THREAD

**Issue by JKP0** [facebookresearch/TreeNLG#9]
Please can you provide the prediction guideline

**Comment by znculee** [comment]
Please refer to [this section](https://github.com/facebookresearch/TreeNLG#constrained-decoding) to reproduce the results by using the provided scripts. Particularly for prediction, you may want to focus on the script of the name starting with `generate.`.

**Comment by JKP0** [comment]
Thanks @znculee 
We are looking for a prediction on outer data. 
Let me check with `generate.`

**Comment by znculee** [comment]
Speaking of using outer data, you may check the `prepare.` scripts and revise them for your own purposes.

**Comment by JKP0** [comment]
Using your own data, you have convert your data tree stracture, for which script /function is not provided/implemented.
